.PHONY: clean All

All:
	@echo "----------Building project:[ HelloWorld_P13Project - Debug ]----------"
	@cd "HelloWorld_P13Project" && "$(MAKE)" -f  "HelloWorld_P13Project.mk"
clean:
	@echo "----------Cleaning project:[ HelloWorld_P13Project - Debug ]----------"
	@cd "HelloWorld_P13Project" && "$(MAKE)" -f  "HelloWorld_P13Project.mk" clean
