.PHONY: clean All

All:
	@echo "----------Building project:[ Examples - Debug ]----------"
	@cd "Examples" && "$(MAKE)" -f  "Examples.mk"
clean:
	@echo "----------Cleaning project:[ Examples - Debug ]----------"
	@cd "Examples" && "$(MAKE)" -f  "Examples.mk" clean
